#!/bin/bash

# 注:ポート番号は固定
docker run -it --rm \
  --name sackerel \
  -p 39700:39700 \
  -e SAKURACLOUD_ACCESS_TOKEN \
  -e SAKURACLOUD_ACCESS_TOKEN_SECRET \
  -e SAKURACLOUD_ZONES \
  -e SAKURACLOUD_TRACE_MODE \
  -e MACKEREL_APIKEY \
  -e MACKEREL_TRACE_MODE \
  -e SACKEREL_TIMER_JOB_INTERVAL \
  -e SACKEREL_COLLECT_METRICS_DURATION \
  -e SACKEREL_API_CALL_INTERVAL \
  -e SACKEREL_JOB_QUEUE_SIZE \
  -e SACKEREL_SAKURA_API_REQEST_QUEUE_SIZE \
  -e SACKEREL_MACKEREL_API_REQEST_QUEUE_SIZE \
  -e SACKEREL_DISABLE_HEALTHCHECK \
  -e SACKEREL_SKIP_INIT \
  -e SACKEREL_TRACE_LOG \
  -e SACKEREL_INFO_LOG \
  -e SACKEREL_WARN_LOG \
  -e SACKEREL_ERROR_LOG \
  -e GODEBUG="http2client=0" \
  sackerel:latest $@